### ISSUE TITLE
为什么要createFakeHttpsWebSite呢？

### ISSUE THREAD

**Issue by lumixraku** [wuchangming/https-mitm-proxy-handbook#5]
为什么要createFakeHttpsWebSite呢？
浏览器在发送 HTTPS 请求的时候会校验证书和域名是否匹配
所以要创建一个假的服务，这个服务所使用的证书的域名就是所代理的域名？

比如一个支持拦截 https 的代理
我请求 a.com 的时候 创建一个假的 https 服务，这个证书对应的域名是a.com  
然后这个假的 https 服务再做一些处理，返回响应给浏览器？这样做到的 https 拦截？

**Comment by wuchangming** [comment]
@lumixraku ，你的理解是对的
